version: '3.9'

services:
  afonsystem:
    build: .
    container_name: streamlit-afonsystem
    ports:
      - "9991:8501"
    volumes:
      - ./duckdb_exports:/app/duckdb_exports
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
